# -*- coding: utf-8 -*-
"""first tables

Revision ID: 8d46edef2072
Revises: e30589ded8fb
Create Date: 2020-01-29 11:35:18.976480

"""

from __future__ import unicode_literals, absolute_import

# revision identifiers, used by Alembic.
revision = '8d46edef2072'
down_revision = 'e30589ded8fb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import rattail.db.types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_items',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('recipes',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('plu', sa.String(length=13), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('recipe_items')
    # ### end Alembic commands ###
