# -*- coding: utf-8 -*-
"""empty message

Revision ID: e30589ded8fb
Revises: f3c39b59e898
Create Date: 2020-01-29 10:16:13.833274

"""

from __future__ import unicode_literals, absolute_import

# revision identifiers, used by Alembic.
revision = 'e30589ded8fb'
down_revision = 'f3c39b59e898'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import rattail.db.types



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratatouille_customer',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('mail_list_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['customer.uuid'], name='ratatouille_customer_fk_customer'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratatouille_customer')
    # ### end Alembic commands ###
